<?php

/**
 * PluginPiQuizPredefinedAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPiQuizPredefinedAnswerTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPiQuizPredefinedAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPiQuizPredefinedAnswer');
    }
}