<?php

/**
 * PluginPiQuizPrizeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPiQuizPrizeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPiQuizPrizeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPiQuizPrize');
    }
}