<?php

/**
 * PluginPiQuizResponse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPiQuizResponse extends BasePiQuizResponse
{
  public function isOpenAnswerMatching($correct_answer)
  {
    if (trim(strtolower($correct_answer)) == trim(strtolower($this->open_answer))) {
      return true;
    } else if (stristr(trim($this->open_answer), trim($correct_answer)) !== false) {
      return true;
    } else {
      return false;
    }
  }
}