<?php

/**
 * PluginPiQuizResponseAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPiQuizResponseAnswerTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPiQuizResponseAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPiQuizResponseAnswer');
    }
}