<?php

/**
 * PluginPiQuizResponseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPiQuizResponseTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPiQuizResponseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPiQuizResponse');
    }
}