generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: PiQuizPredefinedAnswer
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: predefined_answer
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_correct:
          label: Correct
      list:
        display:
          - '=answer'
          - quiz_id
          - is_correct
        sort:
          - answer
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - answer
          - is_correct
          - quiz_id
      form:
        display:
          NONE: [answer, is_correct, quiz_id]
        class: PiQuizPredefinedAnswerAdminForm
        fields: {  }
      edit: ~
      new: ~
